pub const PROTOCOL_VERSION: u32 = 1;

pub const RPC_METHODS: &[&str] = &[
    "app.getStatus",
    "app.getVersion",
    "app.shutdown",
    "settings.get",
    "settings.update",
    "settings.reset",
    "credentials.hasApiKey",
    "credentials.setApiKey",
    "credentials.deleteApiKey",
    "audio.listDevices",
    "audio.selectDevice",
    "audio.startPreview",
    "audio.stopPreview",
    "hotkey.get",
    "hotkey.set",
    "hotkey.register",
    "hotkey.unregister",
    "dictation.start",
    "dictation.stop",
    "dictation.cancel",
    "dictation.retryLast",
    "dictation.copyLastTranscript",
    "dictation.injectLastTranscript",
    "permissions.getStatus",
    "permissions.request",
    "diagnostics.get",
    "diagnostics.export",
];

pub const RPC_NOTIFICATIONS: &[&str] = &[
    "status.changed",
    "recording.started",
    "recording.level",
    "recording.stopped",
    "transcription.partial",
    "transcription.completed",
    "polish.started",
    "polish.completed",
    "injection.completed",
    "injection.failed",
    "hotkey.registrationFailed",
    "audio.deviceChanged",
    "error.occurred",
];

/// Generate the TypeScript method names and transport types from this crate's
/// canonical protocol declaration.
#[must_use]
pub fn generate_typescript_contract() -> String {
    fn array(values: &[&str]) -> String {
        values
            .iter()
            .map(|value| format!("  '{value}'"))
            .collect::<Vec<_>>()
            .join(",\n")
    }

    format!(
        "// Generated by freeflow-rpc. Do not edit.\n\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n\n\
         export const RPC_METHODS = [\n\
         {}\n\
         ] as const;\n\
         export type RpcMethod = (typeof RPC_METHODS)[number];\n\n\
         export const RPC_NOTIFICATION_METHODS = [\n\
         {}\n\
         ] as const;\n\
         export type RpcNotificationMethod = (typeof RPC_NOTIFICATION_METHODS)[number];\n\n\
         export interface JsonRpcRequest<P = unknown> {{\n\
           jsonrpc: '2.0';\n\
           id: number;\n\
           method: RpcMethod;\n\
           params?: P;\n\
         }}\n\n\
         export interface JsonRpcError {{\n\
           code: number;\n\
           message: string;\n\
           data?: unknown;\n\
         }}\n\n\
         export interface JsonRpcResponse<R = unknown> {{\n\
           jsonrpc: '2.0';\n\
           id: number | null;\n\
           result?: R;\n\
           error?: JsonRpcError;\n\
         }}\n\n\
         export interface RpcNotification<P = unknown> {{\n\
           jsonrpc: '2.0';\n\
           method: RpcNotificationMethod;\n\
           params?: P;\n\
         }}\n",
        array(RPC_METHODS),
        array(RPC_NOTIFICATIONS)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_contains_every_method_once() {
        let contract = generate_typescript_contract();
        for method in RPC_METHODS.iter().chain(RPC_NOTIFICATIONS) {
            assert_eq!(contract.matches(method).count(), 1, "{method}");
        }
    }
}
