// Generated by freeflow-rpc. Do not edit.

export const PROTOCOL_VERSION = 1 as const;

export const RPC_METHODS = [
  'app.getStatus',
  'app.getVersion',
  'app.shutdown',
  'settings.get',
  'settings.update',
  'settings.reset',
  'credentials.hasApiKey',
  'credentials.setApiKey',
  'credentials.deleteApiKey',
  'audio.listDevices',
  'audio.selectDevice',
  'audio.startPreview',
  'audio.stopPreview',
  'hotkey.get',
  'hotkey.set',
  'hotkey.register',
  'hotkey.unregister',
  'dictation.start',
  'dictation.stop',
  'dictation.cancel',
  'dictation.retryLast',
  'dictation.copyLastTranscript',
  'dictation.injectLastTranscript',
  'permissions.getStatus',
  'permissions.request',
  'diagnostics.get',
  'diagnostics.export'
] as const;
export type RpcMethod = (typeof RPC_METHODS)[number];

export const RPC_NOTIFICATION_METHODS = [
  'status.changed',
  'recording.started',
  'recording.level',
  'recording.stopped',
  'transcription.partial',
  'transcription.completed',
  'polish.started',
  'polish.completed',
  'injection.completed',
  'injection.failed',
  'hotkey.registrationFailed',
  'audio.deviceChanged',
  'error.occurred'
] as const;
export type RpcNotificationMethod = (typeof RPC_NOTIFICATION_METHODS)[number];

export interface JsonRpcRequest<P = unknown> {
jsonrpc: '2.0';
id: number;
method: RpcMethod;
params?: P;
}

export interface JsonRpcError {
code: number;
message: string;
data?: unknown;
}

export interface JsonRpcResponse<R = unknown> {
jsonrpc: '2.0';
id: number | null;
result?: R;
error?: JsonRpcError;
}

export interface RpcNotification<P = unknown> {
jsonrpc: '2.0';
method: RpcNotificationMethod;
params?: P;
}
